### ISSUE TITLE
Create Custom Widget for Repeated TextField Code

### ISSUE THREAD

**Issue by Priyammm05** [cynthiakonar/proximity_picks#1]
**Issue Description:**
In our codebase, we've noticed that there are multiple instances where TextField widgets are used with similar configurations and properties. This repetition not only makes the code less maintainable but also increases the chances of inconsistencies and bugs. To improve code organization and reduce redundancy, we should create a custom widget that encapsulates the common TextField configurations.

P**roposed Solution:**
We propose creating a custom TextField widget that allows us to set common properties like input decoration, controller, validator, and more in a single place. This custom widget will simplify the code, improve consistency, and make it easier to maintain.

**Benefits:**

- Improved code readability and maintainability.
- Reduced code duplication and potential bugs.
- Enhanced consistency in the UI.

**Comment by Priyammm05** [comment]
Can I work on this for hacktoberfest @cynthiakonar

**Comment by cynthiakonar** [comment]
> Can I work on this for hacktoberfest @cynthiakonar

Sure, go ahead @Priyammm05 
Please fork this repository and create a PR for your changes. Also make sure to link this issue with your PR.

**Comment by as3hr** [comment]
Can I also contribute to this issue @cynthiakonar if it is not done @Priyammm05
